#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { getClientIconMap, ALIASES, STROKE_WIDTH, DEFAULT_SIZE } = require("../src/icons");

const OUT = path.join(__dirname, "..", "public", "js", "icons.js");

function main() {
    const icons = getClientIconMap();
    const payload = JSON.stringify(
        {
            strokeWidth: STROKE_WIDTH,
            defaultSize: DEFAULT_SIZE,
            aliases: ALIASES,
            icons,
        },
        null,
        4
    );

    const source = `/* Generated by scripts/build-icons.js — do not edit by hand. */
(function (root) {
    "use strict";

    var DATA = ${payload};

    function resolveName(name) {
        var raw = String(name || "circle").trim().toLowerCase();
        return DATA.aliases[raw] || raw;
    }

    function svg(name, opts) {
        opts = opts || {};
        var official = resolveName(name);
        var inner = DATA.icons[official] || DATA.icons.circle || "";
        var size = Number(opts.size) > 0 ? Number(opts.size) : DATA.defaultSize;
        var extra = opts.className || opts.icoClass || "";
        var cls = ("ico " + extra).trim();
        var title = opts.title ? String(opts.title) : "";
        var a11y = title
            ? ' role="img" aria-label="' + title.replace(/"/g, "&quot;") + '"'
            : ' aria-hidden="true"';

        return '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size + '"'
            + ' viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="' + DATA.strokeWidth + '"'
            + ' stroke-linecap="round" stroke-linejoin="round" class="' + cls + '"'
            + ' data-lucide="' + official + '"' + a11y + '>' + inner + '</svg>';
    }

    root.Icons = { svg: svg, resolveName: resolveName };
})(typeof window !== "undefined" ? window : this);
`;

    fs.writeFileSync(OUT, source);
    console.log("Wrote", OUT, "with", Object.keys(icons).length, "Lucide icons");
}

main();
